const STORE={reviews:'cc_reviews_v2',owner:'cc_owner_v2',clients:'cc_clients_v2'};
const WA='27716369939',EMAIL='Davianbenjamin67@gmail.com';
const sponsorship=[
 ['img','assets/img/sponsor-01.jpg','LEGENDS BARBER • PHOTO 01'],['img','assets/img/sponsor-02.jpg','LEGENDS BARBER • PHOTO 02'],['img','assets/img/sponsor-03.jpg','LEGENDS BARBER • PHOTO 03'],['img','assets/img/sponsor-04.jpg','LEGENDS BARBER • PHOTO 04'],['img','assets/img/sponsor-05.jpg','LEGENDS BARBER • PHOTO 05'],
 ['video','assets/video/VID-20260818-WA0023.mp4','LEGENDS BARBER • VIDEO 01','assets/posters/VID-20260818-WA0023.jpg'],['video','assets/video/VID-20260818-WA0024.mp4','LEGENDS BARBER • VIDEO 02','assets/posters/VID-20260818-WA0024.jpg'],['video','assets/video/VID-20260818-WA0027.mp4','LEGENDS BARBER • VIDEO 03','assets/posters/VID-20260818-WA0027.jpg'],['video','assets/video/VID-20260818-WA0080.mp4','LEGENDS BARBER • VIDEO 04','assets/posters/VID-20260818-WA0080.jpg'],['video','assets/video/VID-20260818-WA0082.mp4','LEGENDS BARBER • VIDEO 05','assets/posters/VID-20260818-WA0082.jpg']
];
const get=(k,d)=>{try{return JSON.parse(localStorage.getItem(k))??d}catch{return d}};const set=(k,v)=>localStorage.setItem(k,JSON.stringify(v));const esc=s=>String(s??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));const stars=n=>'★★★★★'.slice(0,n)+'☆☆☆☆☆'.slice(0,5-n);
function slideshow(root,items){const slides=root.querySelector('.slides'),dots=root.querySelector('.dots');let i=0;slides.innerHTML=items.map((x,n)=>x[0]==='img'?`<figure class="slide ${n===0?'active':''}"><img src="${x[1]}" alt="${esc(x[2])}"><figcaption>${esc(x[2])}</figcaption></figure>`:`<figure class="slide ${n===0?'active':''}"><video controls playsinline preload="metadata" poster="${x[3]||''}"><source src="${x[1]}" type="video/mp4"></video><figcaption>${esc(x[2])}</figcaption></figure>`).join('');dots.innerHTML=items.map((_,n)=>`<button class="dot ${n===0?'active':''}" aria-label="Go to ${n+1}"></button>`).join('');const go=n=>{i=(n+items.length)%items.length;slides.querySelectorAll('.slide').forEach((s,j)=>s.classList.toggle('active',j===i));dots.querySelectorAll('.dot').forEach((d,j)=>d.classList.toggle('active',j===i));};root.querySelector('.prev').onclick=()=>go(i-1);root.querySelector('.next').onclick=()=>go(i+1);dots.querySelectorAll('.dot').forEach((d,n)=>d.onclick=()=>go(n));let sx=0;slides.addEventListener('touchstart',e=>sx=e.changedTouches[0].screenX,{passive:true});slides.addEventListener('touchend',e=>{let dx=e.changedTouches[0].screenX-sx;if(Math.abs(dx)>45)go(i+(dx<0?1:-1));});}
function booking(){const m=document.getElementById('booking');document.querySelectorAll('[data-book]').forEach(b=>b.onclick=()=>m.classList.add('show'));document.querySelector('[data-close]').onclick=()=>m.classList.remove('show');document.getElementById('bookingForm').onsubmit=e=>{e.preventDefault();const f=new FormData(e.target);const text=`Crosses & Clippers Appointment\n\nName: ${f.get('name')}\nPhone: ${f.get('phone')}\nService: ${f.get('service')}\nDate: ${f.get('date')}\nTime: ${f.get('time')}\nNotes: ${f.get('notes')||'None'}`;window.open(`https://wa.me/${WA}?text=${encodeURIComponent(text)}`,'_blank');window.location.href=`mailto:${EMAIL}?subject=${encodeURIComponent('Crosses & Clippers Appointment')}&body=${encodeURIComponent(text)}`;m.classList.remove('show');};}
function renderReviews(){const rs=get(STORE.reviews,[]).filter(r=>r.approved);const list=document.getElementById('reviewList');document.getElementById('reviewCount').textContent=rs.length;const avg=rs.length?rs.reduce((a,r)=>a+r.rating,0)/rs.length:0;document.getElementById('avgRating').textContent=avg.toFixed(1);document.getElementById('ratingStars').textContent=stars(Math.round(avg));list.innerHTML=rs.length?rs.map(r=>`<article class="review-item"><div class="stars">${stars(r.rating)}</div><h4>${esc(r.name)}</h4><p>${esc(r.comment)}</p><small>${new Date(r.createdAt).toLocaleDateString()}</small></article>`).join(''):'<div class="empty-state">Be the first approved client review.</div>';}
function reviews(){document.getElementById('reviewForm').onsubmit=e=>{e.preventDefault();const f=new FormData(e.target),r={id:crypto.randomUUID(),name:f.get('name'),email:f.get('email'),rating:+f.get('rating'),comment:f.get('comment'),approved:false,createdAt:new Date().toISOString()};const rs=get(STORE.reviews,[]);rs.unshift(r);set(STORE.reviews,rs);const cs=get(STORE.clients,[]);cs.unshift({id:r.id,name:r.name,email:r.email,createdAt:r.createdAt});set(STORE.clients,cs);e.target.reset();renderReviews();alert('Review submitted. Thank you — it will appear after owner approval.');};renderReviews();}
function admin(){const modal=document.getElementById('admin');document.getElementById('adminOpen').onclick=()=>modal.classList.add('show');document.querySelector('[data-admin-close]').onclick=()=>modal.classList.remove('show');document.getElementById('adminLogin').onsubmit=e=>{e.preventDefault();const f=new FormData(e.target),saved=get(STORE.owner,null);if(!saved){set(STORE.owner,{email:f.get('email'),password:f.get('password')});showAdmin();alert('Owner account created on this browser.');}else if(saved.email===f.get('email')&&saved.password===f.get('password'))showAdmin();else alert('Owner login details do not match this browser.');};function showAdmin(){document.getElementById('adminLogin').style.display='none';const panel=document.getElementById('adminPanel');const rs=get(STORE.reviews,[]),cs=get(STORE.clients,[]);panel.innerHTML='<h3>REVIEW MANAGEMENT</h3>'+ (rs.length?rs.map(r=>`<div class="admin-review"><strong>${esc(r.name)} • ${stars(r.rating)}</strong><p>${esc(r.comment)}</p><div class="admin-actions">${r.approved?'':'<button class="approve" data-a="'+r.id+'">APPROVE</button>'}<button data-d="${r.id}">DELETE</button></div></div>`).join(''):'<p>No reviews.</p>')+'<h3 style="margin-top:35px">CLIENT DATABASE</h3>'+cs.map(c=>`<div class="client-row"><strong>${esc(c.name)}</strong><span>${esc(c.email||'No email')}</span></div>`).join('');panel.querySelectorAll('[data-a]').forEach(b=>b.onclick=()=>{const a=get(STORE.reviews,[]),r=a.find(x=>x.id===b.dataset.a);if(r)r.approved=true;set(STORE.reviews,a);renderReviews();showAdmin();});panel.querySelectorAll('[data-d]').forEach(b=>b.onclick=()=>{set(STORE.reviews,get(STORE.reviews,[]).filter(x=>x.id!==b.dataset.d));renderReviews();showAdmin();});}}
slideshow(document.querySelector('[data-slideshow="sponsor"]'),sponsorship);booking();reviews();admin();
