/* Crosses & Clippers V5 enhancement layer. Keeps the V4 HTML/design and adds the requested live review/owner/client workflow. */
(function(){
  const REVIEW_KEY='cc_v5_reviews';
  const CLIENT_KEY='cc_v5_clients';
  const OWNER_KEY='cc_v5_owner';
  const safe=(s)=>String(s||'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
  const get=(k,d)=>{try{return JSON.parse(localStorage.getItem(k))||d}catch(e){return d}};
  const put=(k,v)=>localStorage.setItem(k,JSON.stringify(v));
  const star=n=>'★★★★★'.slice(0,n)+'☆☆☆☆☆'.slice(0,5-n);

  function injectStyle(){
    if(document.getElementById('cc-v5-style'))return;
    const s=document.createElement('style');s.id='cc-v5-style';s.textContent=`
      #ccReviewSystem{max-width:1320px;margin:auto;padding:100px 7vw;background:#0b0b0b}.cc-review-layout{display:grid;grid-template-columns:.8fr 1.2fr;gap:55px}.cc-review-card,.cc-review-form,.cc-owner-card{border:1px solid #292929;background:#111;padding:28px}.cc-review-card{margin-bottom:10px}.cc-review-stars{color:#d5bd8b;letter-spacing:2px}.cc-review-meta{font-size:9px;color:#777;letter-spacing:.08em}.cc-review-card p{color:#aaa;line-height:1.75}.cc-review-form label,.cc-owner-card label{display:grid;gap:7px;font-size:8px;letter-spacing:.15em;color:#777;margin-bottom:12px}.cc-review-form input,.cc-review-form textarea,.cc-review-form select,.cc-owner-card input{padding:13px;border:1px solid #333;background:#080808;color:#f3f0e9;font:inherit}.cc-review-form textarea{min-height:120px}.cc-review-btn{border:1px solid #f3f0e9;background:#f3f0e9;color:#111;padding:14px 18px;font-size:9px;font-weight:700;letter-spacing:.14em;cursor:pointer}.cc-owner-panel{display:none;margin-top:15px}.cc-owner-panel.show{display:block}.cc-admin-row{display:flex;justify-content:space-between;gap:15px;padding:13px 0;border-bottom:1px solid #222;color:#aaa;font-size:11px}.cc-admin-row button{border:1px solid #555;background:none;color:#eee;padding:7px 10px;font-size:8px;cursor:pointer}.cc-admin-row .approve{color:#d5bd8b;border-color:#d5bd8b}.cc-owner-modal{position:fixed;inset:0;background:rgba(0,0,0,.82);z-index:160;display:none;place-items:center;padding:20px}.cc-owner-modal.show{display:grid}.cc-owner-modal>div{width:min(500px,100%);background:#f3f0e9;color:#111;padding:35px}.cc-owner-modal input{display:block;width:100%;padding:13px;margin:7px 0 15px;border:1px solid #ccc}.cc-close{float:right;border:0;background:none;font-size:18px;cursor:pointer}.cc-article-story{margin-top:35px;padding:28px;border:1px solid #292929;background:#111;color:#aaa;line-height:1.85}.cc-article-story strong{color:#d5bd8b}.cc-article-story h3{font-family:Oswald,sans-serif;font-size:42px;color:#f3f0e9;margin:0 0 15px}.cc-story-only-video video{width:100%;min-height:500px;object-fit:cover;display:block}.cc-story-only-video{max-width:1320px;margin:auto;padding:0 7vw 100px;background:#0b0b0b}.cc-story-only-video figcaption{padding:12px 0;font-size:9px;letter-spacing:.15em;color:#777}.cc-hide-story-media{display:none!important}@media(max-width:900px){.cc-review-layout{grid-template-columns:1fr}.cc-story-only-video{padding-left:6vw;padding-right:6vw}.cc-story-only-video video{min-height:380px}}@media(max-width:600px){#ccReviewSystem{padding:80px 6vw}.cc-story-only-video video{min-height:260px}.cc-admin-row{flex-direction:column}}
    `;document.head.appendChild(s);
  }

  function fixMyStory(){
    const story=document.getElementById('story');if(!story)return;
    // Hide all existing My Story image/video gallery material; retain the section text and add exactly one 3-minute video.
    const gallery=document.querySelector('.story-gallery');if(gallery)gallery.remove();
    story.querySelectorAll('img, .story-media').forEach(el=>el.classList.add('cc-hide-story-media'));
    if(!document.getElementById('ccStoryVideo')){
      const wrap=document.createElement('div');wrap.id='ccStoryVideo';wrap.className='cc-story-only-video';
      wrap.innerHTML='<figure style="margin:0"><video controls playsinline preload="metadata" poster="assets/my-story/posters/my-story-01.jpg"><source src="assets/my-story/videos/my-story-01.mp4" type="video/mp4"></video><figcaption>MY STORY • THE FULL 3-MINUTE STORY</figcaption></figure>';
      story.after(wrap);
    }
  }

  function addArticleStory(){
    const sponsor=document.getElementById('sponsorship');if(!sponsor||document.getElementById('ccArticleStory'))return;
    const box=document.createElement('div');box.id='ccArticleStory';box.className='cc-article-story';
    box.innerHTML='<h3>A GIFT THAT MEANT MORE THAN EQUIPMENT.</h3><p><strong>Legends Barber founder Sheldon Tatchell</strong> donated barbershop equipment to an Eden Park youngster. Besides running multiple successful businesses, Sheldon is known for charitable causes aimed at uplifting the youth.</p><p>“Today, I am in Eden Park visiting a barber who just recovered from drug abuse. He now tries to rebuild his life, cutting hair from his home. I came to bless him with equipment, but more than that, I am here to give him hope.”</p><p><strong>— Sheldon Tatchell</strong></p>';
    sponsor.appendChild(box);
  }

  function buildReviews(){
    if(document.getElementById('ccReviewSystem'))return;
    const section=document.createElement('section');section.id='ccReviewSystem';
    section.innerHTML=`<div class="section-title"><p class="eyebrow">CLIENT FEEDBACK</p><h2>REAL <em>REVIEWS.</em></h2></div><div class="cc-review-layout"><div><div class="cc-review-form"><p class="eyebrow">SHARE YOUR EXPERIENCE</p><form id="ccReviewForm"><label>NAME<input name="name" required maxlength="80" placeholder="Your name"></label><label>EMAIL<input name="email" type="email" maxlength="160" placeholder="Optional"></label><label>RATING<select name="rating" required><option value="">Choose</option><option value="5">5 — Excellent</option><option value="4">4 — Great</option><option value="3">3 — Good</option><option value="2">2 — Fair</option><option value="1">1 — Poor</option></select></label><label>COMMENT<textarea name="comment" required maxlength="1200" placeholder="Tell us about your experience"></textarea></label><button class="cc-review-btn" type="submit">SUBMIT REVIEW ↗</button><p class="form-note">Reviews are moderated before appearing publicly.</p></form></div><div class="cc-owner-card" style="margin-top:12px"><p class="eyebrow">OWNER AREA</p><p class="form-note">Owner login manages review approvals and the local client records created through this browser.</p><button class="cc-review-btn" id="ccOwnerOpen">OWNER LOGIN</button><div class="cc-owner-panel" id="ccOwnerPanel"><div id="ccAdminReviews"></div><div id="ccClients" style="margin-top:25px"></div></div></div></div><div id="ccReviewsList"></div></div>`;
    const contact=document.getElementById('contact');contact?contact.before(section):document.querySelector('main').appendChild(section);
    document.getElementById('ccReviewForm').onsubmit=e=>{e.preventDefault();const f=new FormData(e.target);const review={id:crypto.randomUUID?crypto.randomUUID():String(Date.now()),name:f.get('name'),email:f.get('email'),rating:Number(f.get('rating')),comment:f.get('comment'),approved:false,createdAt:new Date().toISOString()};const rs=get(REVIEW_KEY,[]);rs.unshift(review);put(REVIEW_KEY,rs);const clients=get(CLIENT_KEY,[]);clients.unshift({id:review.id,name:review.name,email:review.email,createdAt:review.createdAt});put(CLIENT_KEY,clients);e.target.reset();renderReviews();alert('Thank you. Your review has been submitted for approval.');};
    renderReviews();
  }
  function renderReviews(){const box=document.getElementById('ccReviewsList');if(!box)return;const rs=get(REVIEW_KEY,[]).filter(r=>r.approved);box.innerHTML=rs.length?rs.map(r=>`<article class="cc-review-card"><div class="cc-review-stars">${star(r.rating)}</div><div class="cc-review-meta">${safe(r.name)} • ${new Date(r.createdAt).toLocaleDateString()}</div><p>${safe(r.comment)}</p></article>`).join(''):'<div class="cc-review-card"><p>No approved reviews yet. Be the first to share your experience.</p></div>';if(document.getElementById('ccOwnerPanel')?.classList.contains('show'))renderAdmin();}
  function renderAdmin(){const box=document.getElementById('ccAdminReviews'),clients=document.getElementById('ccClients');if(!box)return;const rs=get(REVIEW_KEY,[]);box.innerHTML='<p class="eyebrow">REVIEW MANAGEMENT</p>'+ (rs.length?rs.map(r=>`<div class="cc-admin-row"><span><b>${safe(r.name)}</b> — ${star(r.rating)}<br>${safe(r.comment)}</span><span>${r.approved?'':'<button class="approve" data-approve="'+r.id+'">APPROVE</button>'}<button data-delete="'+r.id+'">DELETE</button></span></div>`).join(''):'<p>No reviews.</p>');box.querySelectorAll('[data-approve]').forEach(b=>b.onclick=()=>{const a=get(REVIEW_KEY,[]);const r=a.find(x=>x.id===b.dataset.approve);if(r)r.approved=true;put(REVIEW_KEY,a);renderReviews()});box.querySelectorAll('[data-delete]').forEach(b=>b.onclick=()=>{put(REVIEW_KEY,get(REVIEW_KEY,[]).filter(x=>x.id!==b.dataset.delete));renderReviews()});const cs=get(CLIENT_KEY,[]);clients.innerHTML='<p class="eyebrow">CLIENT DATABASE</p><p class="form-note">'+cs.length+' client record(s) stored in this browser.</p>'+cs.map(c=>`<div class="cc-admin-row"><span><b>${safe(c.name)}</b><br>${safe(c.email||'')}</span></div>`).join('');}
  function ownerModal(){const m=document.createElement('div');m.className='cc-owner-modal';m.id='ccOwnerModal';m.innerHTML='<div><button class="cc-close" id="ccOwnerClose">✕</button><p class="eyebrow">PRIVATE AREA</p><h2 style="font-family:Oswald;font-size:55px;margin:10px 0 20px">OWNER <em>LOGIN.</em></h2><form id="ccOwnerForm"><label style="color:#666;font-size:8px;letter-spacing:.15em">EMAIL<input id="ccOwnerEmail" type="email" required></label><label style="color:#666;font-size:8px;letter-spacing:.15em">PASSWORD<input id="ccOwnerPass" type="password" required></label><button class="cc-review-btn" type="submit">SIGN IN</button><p class="form-note">This GitHub Pages fallback keeps owner credentials and client data in this browser. For real private client data, connect Supabase Auth/Database before launch.</p></form></div>';document.body.appendChild(m);document.getElementById('ccOwnerOpen').onclick=()=>m.classList.add('show');document.getElementById('ccOwnerClose').onclick=()=>m.classList.remove('show');document.getElementById('ccOwnerForm').onsubmit=e=>{e.preventDefault();const email=document.getElementById('ccOwnerEmail').value.trim();const pass=document.getElementById('ccOwnerPass').value;if(pass.length<6)return alert('Use at least 6 characters.');const saved=get(OWNER_KEY,null);if(!saved){put(OWNER_KEY,{email,password:pass});openOwner();m.classList.remove('show');alert('Owner account created on this browser.')}else if(saved.email===email&&saved.password===pass){openOwner();m.classList.remove('show')}else alert('Owner login details do not match this browser.')}};
  function openOwner(){document.getElementById('ccOwnerPanel').classList.add('show');renderAdmin();}
  document.addEventListener('DOMContentLoaded',()=>{injectStyle();fixMyStory();addArticleStory();buildReviews();ownerModal();});
})();
