const CFG=window.SUPABASE_CONFIG||{};
const HAS_SUPABASE=Boolean(window.supabase&&CFG.url&&CFG.anonKey&&!String(CFG.url).includes('YOUR_'));
const sb=HAS_SUPABASE?window.supabase.createClient(CFG.url,CFG.anonKey):null;
const WA='27716369939', EMAIL='Davianbenjamin67@gmail.com';
const STORE={reviews:'cc_reviews_v5',clients:'cc_clients_v5',appointments:'cc_appointments_v5',owner:'cc_owner_v5'};
const work=[
 ['img','assets/img/work-01.jpg','MY WORK • CUT 01'],
 ['img','assets/img/work-02.jpg','MY WORK • CUT 02'],
 ['img','assets/img/work-03.jpg','MY WORK • CUT 03'],
 ['video','assets/video/work-04.mp4','MY WORK • VIDEO 04']
];
const sponsorship=[
 ['img','assets/img/sponsor-01.jpg','LEGENDS BARBER • PHOTO 01'],['img','assets/img/sponsor-02.jpg','LEGENDS BARBER • PHOTO 02'],['img','assets/img/sponsor-03.jpg','LEGENDS BARBER • PHOTO 03'],['img','assets/img/sponsor-04.jpg','LEGENDS BARBER • PHOTO 04'],['img','assets/img/sponsor-05.jpg','LEGENDS BARBER • PHOTO 05'],['img','assets/img/sponsor-06.jpg','LEGENDS BARBER • ARTICLE PHOTO'],
 ['video','assets/video/VID-20260818-WA0023.mp4','LEGENDS BARBER • VIDEO 01','assets/posters/VID-20260818-WA0023.jpg'],['video','assets/video/VID-20260818-WA0024.mp4','LEGENDS BARBER • VIDEO 02','assets/posters/VID-20260818-WA0024.jpg'],['video','assets/video/VID-20260818-WA0027.mp4','LEGENDS BARBER • VIDEO 03','assets/posters/VID-20260818-WA0027.jpg'],['video','assets/video/VID-20260818-WA0080.mp4','LEGENDS BARBER • VIDEO 04','assets/posters/VID-20260818-WA0080.jpg'],['video','assets/video/VID-20260818-WA0082.mp4','LEGENDS BARBER • VIDEO 05','assets/posters/VID-20260818-WA0082.jpg'],['video','assets/video/VID-20260818-WA0093.mp4','LEGENDS BARBER • VIDEO 06','assets/posters/VID-20260818-WA0093.jpg'],['video','assets/video/VID-20260818-WA0102.mp4','LEGENDS BARBER • VIDEO 07','assets/posters/VID-20260818-WA0102.jpg'],['video','assets/video/VID-20260818-WA0108.mp4','LEGENDS BARBER • VIDEO 08','assets/posters/VID-20260818-WA0108.jpg']
];
const esc=s=>String(s??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
const stars=n=>{n=Math.max(0,Math.min(5,Number(n)||0));return '★'.repeat(n)+'☆'.repeat(5-n)};
const localGet=(k,d)=>{try{return JSON.parse(localStorage.getItem(k))??d}catch{return d}};
const localSet=(k,v)=>localStorage.setItem(k,JSON.stringify(v));
function slideshow(root,items){if(!root)return;const slides=root.querySelector('.slides'),dots=root.querySelector('.dots'),counter=root.querySelector('.slide-counter');let i=0;slides.innerHTML=items.map((x,n)=>x[0]==='img'?`<figure class="slide ${n===0?'active':''}"><img src="${x[1]}" alt="${esc(x[2])}" loading="${n?'lazy':'eager'}"><figcaption>${esc(x[2])}</figcaption></figure>`:`<figure class="slide ${n===0?'active':''}"><video controls playsinline preload="none"><source src="${x[1]}" type="video/mp4"></video><figcaption>${esc(x[2])}</figcaption></figure>`).join('');dots.innerHTML=items.map((_,n)=>`<button class="dot ${n===0?'active':''}" aria-label="Go to media ${n+1}"></button>`).join('');const go=n=>{i=(n+items.length)%items.length;slides.querySelectorAll('.slide').forEach((s,j)=>{s.classList.toggle('active',j===i);if(j!==i){const v=s.querySelector('video');if(v)v.pause()}});dots.querySelectorAll('.dot').forEach((d,j)=>d.classList.toggle('active',j===i));if(counter)counter.textContent=`${String(i+1).padStart(2,'0')} / ${String(items.length).padStart(2,'0')}`};root.querySelector('.prev').onclick=()=>go(i-1);root.querySelector('.next').onclick=()=>go(i+1);dots.querySelectorAll('.dot').forEach((d,n)=>d.onclick=()=>go(n));let sx=0;slides.addEventListener('touchstart',e=>sx=e.changedTouches[0].screenX,{passive:true});slides.addEventListener('touchend',e=>{const dx=e.changedTouches[0].screenX-sx;if(Math.abs(dx)>45)go(i+(dx<0?1:-1))});root.addEventListener('keydown',e=>{if(e.key==='ArrowLeft')go(i-1);if(e.key==='ArrowRight')go(i+1)});root.tabIndex=0;go(0)}
function notify(message){let t=document.querySelector('.toast');if(!t){t=document.createElement('div');t.className='toast';document.body.appendChild(t)}t.textContent=message;t.classList.add('show');setTimeout(()=>t.classList.remove('show'),3200)}
function booking(){const modal=document.getElementById('booking'),form=document.getElementById('bookingForm'),view=document.getElementById('bookingFormView'),previewView=document.getElementById('bookingPreviewView'),preview=document.getElementById('bookingPreview'),wa=document.getElementById('sendWhatsApp'),mail=document.getElementById('sendEmail');document.querySelectorAll('[data-book]').forEach(b=>b.onclick=()=>{modal.classList.add('show');view.hidden=false;previewView.hidden=true});document.querySelector('[data-close]').onclick=()=>modal.classList.remove('show');const reset=()=>{view.hidden=false;previewView.hidden=true;form.reset()};document.getElementById('editBooking').onclick=reset;form.onsubmit=async e=>{e.preventDefault();const f=new FormData(form),name=String(f.get('name')).trim(),phone=String(f.get('phone')).trim(),service=String(f.get('service')),date=String(f.get('date')),time=String(f.get('time')),notes=String(f.get('notes')||'').trim();const text=`Crosses & Clippers Appointment\n\nName: ${name}\nPhone: ${phone}\nService: ${service}\nDate: ${date}\nTime: ${time}\nNotes: ${notes||'None'}`;preview.textContent=text;wa.href=`https://wa.me/${WA}?text=${encodeURIComponent(text)}`;mail.href=`mailto:${EMAIL}?subject=${encodeURIComponent('Crosses & Clippers Appointment')}&body=${encodeURIComponent(text)}`;const row={name,phone,service,date,time,notes,status:'new',created_at:new Date().toISOString()};try{if(sb){await sb.from('appointments').insert(row);await sb.from('clients').insert({name,phone,notes})}else{const cs=localGet(STORE.clients,[]);cs.unshift({...row,id:crypto.randomUUID()});localSet(STORE.clients,cs);const ap=localGet(STORE.appointments,[]);ap.unshift({...row,id:crypto.randomUUID()});localSet(STORE.appointments,ap)}}catch(err){console.warn(err)}view.hidden=true;previewView.hidden=false}};
async function fetchApprovedReviews(){if(sb){const {data,error}=await sb.from('reviews').select('*').eq('status','approved').order('created_at',{ascending:false});if(!error)return data||[];console.warn(error)}return localGet(STORE.reviews,[]).filter(r=>r.status==='approved'||r.approved===true).sort((a,b)=>new Date(b.created_at||b.createdAt)-new Date(a.created_at||a.createdAt))}
async function renderReviews(){const rs=await fetchApprovedReviews(),list=document.getElementById('reviewList');document.getElementById('reviewCount').textContent=rs.length;const avg=rs.length?rs.reduce((a,r)=>a+Number(r.rating),0)/rs.length:0;document.getElementById('avgRating').textContent=avg.toFixed(1);document.getElementById('ratingStars').textContent=stars(Math.round(avg));list.innerHTML=rs.length?rs.map(r=>`<article class="review-item"><div class="stars">${stars(r.rating)}</div><h4>${esc(r.name)}</h4><p>${esc(r.comment)}</p><small>${new Date(r.created_at||r.createdAt).toLocaleDateString('en-ZA',{day:'2-digit',month:'short',year:'numeric'})}</small></article>`).join(''):'<div class="empty-state">No published reviews yet. Be the first to share your experience.</div>'}
function setupStars(){const buttons=[...document.querySelectorAll('.star-picker button')],value=document.getElementById('ratingValue');buttons.forEach(b=>b.onclick=()=>{const n=+b.dataset.rate;value.value=n;buttons.forEach(x=>x.classList.toggle('active',+x.dataset.rate<=n))})}
async function submitReview(row){if(sb){const {error}=await sb.from('reviews').insert({name:row.name,email:row.email||null,rating:row.rating,comment:row.comment,status:'pending'});if(error)throw error;return}const rs=localGet(STORE.reviews,[]);rs.unshift({id:crypto.randomUUID(),...row,status:'pending',created_at:new Date().toISOString()});localSet(STORE.reviews,rs)}
function reviews(){setupStars();document.getElementById('reviewForm').onsubmit=async e=>{e.preventDefault();const f=new FormData(e.target),rating=Number(f.get('rating'));if(!rating){notify('Please choose a star rating.');return}try{await submitReview({name:String(f.get('name')).trim(),email:String(f.get('email')||'').trim(),rating,comment:String(f.get('comment')).trim()});e.target.reset();document.querySelectorAll('.star-picker button').forEach(x=>x.classList.remove('active'));document.getElementById('reviewStatus').textContent='Thank you. Your review has been submitted for approval.';notify('Review submitted successfully.');await renderReviews()}catch(err){console.error(err);notify('We could not submit the review. Please try again.')}};renderReviews()}
async function getOwnerSession(){if(sb){const {data}=await sb.auth.getSession();return data.session}return localGet(STORE.owner,null)?{local:true}:null}
async function admin(){const modal=document.getElementById('admin'),loginView=document.getElementById('adminLoginView'),panel=document.getElementById('adminPanel'),form=document.getElementById('adminLogin');document.getElementById('adminOpen').onclick=()=>modal.classList.add('show');document.querySelector('[data-admin-close]').onclick=()=>modal.classList.remove('show');form.onsubmit=async e=>{e.preventDefault();const f=new FormData(form),email=String(f.get('email')).trim(),password=String(f.get('password'));try{if(sb){const {error}=await sb.auth.signInWithPassword({email,password});if(error)throw error}else{const saved=localGet(STORE.owner,null);if(!saved)localSet(STORE.owner,{email,password});else if(saved.email!==email||saved.password!==password)throw new Error('Invalid owner login')}loginView.hidden=true;panel.hidden=false;await showAdmin()}catch(err){document.getElementById('adminStatus').textContent=err.message||'Login failed.'}};const session=await getOwnerSession();if(session){loginView.hidden=true;panel.hidden=false;showAdmin()}
async function showAdmin(){let reviewsData=[],clients=[],appointments=[];if(sb){const r=await sb.from('reviews').select('*').order('created_at',{ascending:false});reviewsData=r.data||[];const c=await sb.from('clients').select('*').order('created_at',{ascending:false});clients=c.data||[];const a=await sb.from('appointments').select('*').order('created_at',{ascending:false});appointments=a.data||[]}else{reviewsData=localGet(STORE.reviews,[]);clients=localGet(STORE.clients,[]);appointments=localGet(STORE.appointments,[])}panel.innerHTML=`<div class="admin-tabs"><button class="active" data-tab="reviews">REVIEWS (${reviewsData.length})</button><button data-tab="clients">CLIENTS (${clients.length})</button><button data-tab="appointments">APPOINTMENTS (${appointments.length})</button></div><div id="adminContent"></div>`;const content=panel.querySelector('#adminContent');const renderTab=tab=>{panel.querySelectorAll('.admin-tabs button').forEach(b=>b.classList.toggle('active',b.dataset.tab===tab));if(tab==='reviews')content.innerHTML=reviewsData.length?reviewsData.map(r=>`<div class="admin-review"><div><strong>${esc(r.name)} • ${stars(r.rating)}</strong> <span class="status-pill">${esc(r.status||'pending')}</span></div><p>${esc(r.comment)}</p><div class="admin-actions">${r.status!=='approved'?`<button class="approve" data-approve="${r.id}">APPROVE</button>`:''}${r.status!=='rejected'?`<button data-reject="${r.id}">REJECT</button>`:''}<button data-delete-review="${r.id}">DELETE</button></div></div>`).join(''):'<p class="muted">No reviews yet.</p>';if(tab==='clients')content.innerHTML=clients.length?clients.map(c=>`<div class="client-row"><strong>${esc(c.name)}</strong><span>${esc(c.phone||c.email||'No contact')}</span><span>${esc(c.email||'')}</span><span>${new Date(c.created_at||c.createdAt).toLocaleDateString('en-ZA')}</span></div>`).join(''):'<p class="muted">No client records yet.</p>';if(tab==='appointments')content.innerHTML=appointments.length?appointments.map(a=>`<div class="appointment-row"><strong>${esc(a.name)} • ${esc(a.service)}</strong><span>${esc(a.date)} at ${esc(a.time)}</span><span>${esc(a.phone)}</span><span>${esc(a.notes||'No notes')}</span></div>`).join(''):'<p class="muted">No appointments recorded yet.</p>'};renderTab('reviews');panel.querySelectorAll('[data-tab]').forEach(b=>b.onclick=()=>renderTab(b.dataset.tab));panel.querySelectorAll('[data-approve]').forEach(b=>b.onclick=async()=>{await setReviewStatus(b.dataset.approve,'approved');await showAdmin();await renderReviews()});panel.querySelectorAll('[data-reject]').forEach(b=>b.onclick=async()=>{await setReviewStatus(b.dataset.reject,'rejected');await showAdmin()});panel.querySelectorAll('[data-delete-review]').forEach(b=>b.onclick=async()=>{await deleteReview(b.dataset.deleteReview);await showAdmin();await renderReviews()})}
async function setReviewStatus(id,status){if(sb)await sb.from('reviews').update({status}).eq('id',id);else{const rs=localGet(STORE.reviews,[]);const r=rs.find(x=>x.id===id);if(r)r.status=status;localSet(STORE.reviews,rs)}}async function deleteReview(id){if(sb)await sb.from('reviews').delete().eq('id',id);else localSet(STORE.reviews,localGet(STORE.reviews,[]).filter(r=>r.id!==id))}}
slideshow(document.querySelector('[data-slideshow="work"]'),work);slideshow(document.querySelector('[data-slideshow="sponsor"]'),sponsorship);booking();reviews();admin();
